# pyproject.toml
[tool.kedro]
package_name = "data_pipeline"
project_name = "Restaurant Data Pipeline"
source_dir = "src"
kedro_init_version = "1.0.0"
[tool.kedro_telemetry]
project_id = "2313b90c19484b5ea76448f779172ef3"
